name: pokedex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  graphql_flutter: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.0.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  connectivity_plus: 6.1.5
  intl: 0.20.2
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^5.0.0

flutter:
  # Para usar los iconos de Material
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/maps/regions/kanto/
    - assets/maps/regions/johto/
    - assets/maps/regions/hoenn/
    - assets/maps/regions/sinnoh/
    - assets/maps/regions/unova/
    - assets/maps/regions/kalos/
    - assets/maps/regions/alola/
    - assets/maps/regions/galar/
    - assets/maps/regions/hisui/
    - assets/maps/regions/paldea/
    - assets/maps/test_spawns/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  generate: true

